name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-cicd-app .

      - name: Run Docker Container
        run: docker run -d -p 8080:80 --name test-container my-cicd-app

      - name: Wait for Application
        run: sleep 5

      - name: Test Application
        run: curl --fail http://localhost:8080

      - name: Stop Container
        if: always()
        run: docker stop test-container